"""Backend-neutral browser adapter contracts and implementations."""

from .base import (
    BackendAction,
    BackendActionEvidence,
    BackendActionOutcome,
    BackendArtifactPayload,
    BackendConsoleEntry,
    BackendDevtoolsQuery,
    BackendDevtoolsResult,
    BackendDialogSnapshot,
    BackendDownloadSnapshot,
    BackendDownloadsResult,
    BackendDomEntry,
    BackendNetworkEntry,
    BackendPageSnapshot,
    BackendStatus,
    BackendPerformanceEntry,
    BackendStyleEntry,
    BackendTabSnapshot,
    BackendTabsResult,
    BrowserBackend,
    RawInteractiveElement,
)
from .legacy import LegacyPilotBackend

__all__ = [
    "BackendAction",
    "BackendActionEvidence",
    "BackendActionOutcome",
    "BackendArtifactPayload",
    "BackendConsoleEntry",
    "BackendDevtoolsQuery",
    "BackendDevtoolsResult",
    "BackendDialogSnapshot",
    "BackendDownloadSnapshot",
    "BackendDownloadsResult",
    "BackendDomEntry",
    "BackendNetworkEntry",
    "BackendPageSnapshot",
    "BackendStatus",
    "BackendPerformanceEntry",
    "BackendStyleEntry",
    "BackendTabSnapshot",
    "BackendTabsResult",
    "BrowserBackend",
    "LegacyPilotBackend",
    "RawInteractiveElement",
]
